### ISSUE TITLE
Relation to http://definitelytyped.org/

### ISSUE THREAD

**Issue by hailwood** [types/_discussions#2]
Hey folks,

from what I see this project seems to have a similar goal to http://definitelytyped.org/ I'm just curious as to why we have the split and why I would use this over definitelytyped?

Cheers!

**Comment by felixfbecker** [comment]
DT is a monorepo, types is decentralized. It's an architectural difference. But DT was taken over by MS so that is now the official registry.

**Comment by unional** [comment]
We were hoping some movement for https://github.com/Microsoft/types-publisher/issues/4

But we have been waiting for a very long time.

**Comment by hailwood** [comment]
Gotcha, that issue clears it up pretty nicely and your reasoning is solid.

Appreciate your response. I'll definitely be looking using @types typings in the future.
